### ISSUE TITLE
是否计划加入mega menu的支持

### ISSUE THREAD

**Issue by etherfurnace** [zhwangart/hexo-theme-acorn#13]
企业主题一般都会有mega menu这种样式，是否考虑加入mega menu的支持呀

**Comment by zhwangart** [comment]
> 企业主题一般都会有mega menu这种样式，是否考虑加入mega menu的支持呀

这题超纲了，感兴趣一起开发下？

**Comment by Joe-2002** [comment]
> > 企业主题一般都会有mega menu这种样式，是否考虑加入mega menu的支持呀
> 
> 这题超纲了，感兴趣一起开发下？
可以可以，我打算用这个建站，希望作者有机会可以合作更新
