### ISSUE TITLE
products 和 projects 可能混淆？

### ISSUE THREAD

**Issue by sli1989** [zhwangart/hexo-theme-acorn#2]
`projects.ejs` 应该移动到 `layout\_partial`
无法调用 `products.yml`

---

还有如何生成post的首页预览小框，感觉像`archive-post`，但不会使用

**Comment by zhwangart** [comment]
> 
1. 这个名字，我再用的散装水平英语来想想有没有更合适的；
2. 封面图需要在 post 的 Front-matter 中定义一个图片，这个我后期会在文档中详细写明，例如：

```md
---
title: 
date: 
photos: [
  ["/images/path/xxx.png"]
] 
---
```

**Comment by sli1989** [comment]
方便分享demo的源代码吗。有些问题调试不出来。

**Comment by sli1989** [comment]
我现在遇到的问题是：site.data 模板无法复现首页的 `archive-post.ejs` 样式。

**Comment by zhwangart** [comment]
> 方便分享demo的源代码吗。有些问题调试不出来。
> 我现在遇到的问题是：site.data 模板无法复现首页的 `archive-post.ejs` 样式。

我看到你的第一条留言就已经开始准备样例数据了，并且也优化了一下主题代码。改动比较大，如果你现在已经对主题做了一些修改，更新的时候一定要注意备份。[样例数据点这里](https://github.com/zhwangart/acorn-sample-data)

**Comment by sli1989** [comment]
好的，感谢啦。
