### ISSUE TITLE
关于底部的友情链接

### ISSUE THREAD

**Issue by b2cstory** [zhwangart/hexo-theme-acorn#6]
您好，关于底部的友情链接，如果不输入链接的话确实不会显示链接，但“友情链接”这个 h5 标题依旧会显示，请问是否有办法可以移除呢？谢谢！

**Comment by zhwangart** [comment]
> 您好，关于底部的友情链接，如果不输入链接的话确实不会显示链接，但“友情链接”这个 h5 标题依旧会显示，请问是否有办法可以移除呢？谢谢！

这个需要修改模版文件：layout/_partial/footer.ejs
如果需要调整布局可以参考文档：[https://acorn.imaging.xin/docs/grid.html](https://acorn.imaging.xin/docs/grid.html)

**Comment by b2cstory** [comment]
> > 您好，关于底部的友情链接，如果不输入链接的话确实不会显示链接，但“友情链接”这个 h5 标题依旧会显示，请问是否有办法可以移除呢？谢谢！
> 
> 这个需要修改模版文件：layout/_partial/footer.ejs 如果需要调整布局可以参考文档：https://acorn.imaging.xin/docs/grid.html

谢谢，我研究一下看看～
