### ISSUE TITLE
Google Search Console提示“可点击元素之间的距离太近”

### ISSUE THREAD

**Issue by tufu9441** [zhwangart/hexo-theme-acorn#7]
使用该模板搭建的网站，谷歌站长工具会提示在移动设备易用性上有问题：可点击元素之间的距离太近，据说长期不修复的话可能会影响在搜索结果中的排名。

**Comment by zhwangart** [comment]
> 使用该模板搭建的网站，谷歌站长工具会提示在移动设备易用性上有问题：可点击元素之间的距离太近，据说长期不修复的话可能会影响在搜索结果中的排名。

有无提示哪些可点击元素？

**Comment by tufu9441** [comment]
抱歉是我乌龙了，并不是主题的问题，应该是我robots.txt中禁止了对js和css的抓取导致的。
